version: '3.1'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  lengoo:
    build: .
    ports:
      - 4000:4000
    depends_on: 
      - mongo
    env_file:
      ./.env
    environment:
      - PORT=4000
      - MONGO_URI=mongodb://mongo:27017/lengoo
      - EMAIL=$EMAIL
      - EMAIL_PASSWORD=$EMAIL_PASSWORD

    

    


  

